### ISSUE TITLE
Does not save music folders

### ISSUE THREAD

**Issue by Alllgator343** [flathub/io.bassi.Amberol#3]
After restarting the player, the playlist is empty

Version player: 0.9.1

Installed via flatpak

System:
  Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
  Kernel: 5.15.0-52-generic x86_64 bits: 64 compiler: gcc v: 11.2.0 
  Desktop: Xfce 4.16.0
  tk: Gtk 3.24.23 wm: xfwm dm: LightDM

**Comment by hfiguiere** [comment]
It's the expected behaviour.

**Comment by Alllgator343** [comment]
> It's the expected behaviour.

Because it uses a flatpak?

**Comment by Titaniumtown** [comment]
> > It's the expected behaviour.
> 
> Because it uses a flatpak?

@hfiguiere read this, very sad the author doesn't want to add it https://gitlab.gnome.org/World/amberol/-/issues/154

**Comment by matinwd** [comment]
Anyone able to fork this project and add this feature to store user music player directory? I only want to use it because it has a good looking ui. it has no more feature

**Comment by hfiguiere** [comment]
the latest version actually implement this.

**Comment by Alllgator343** [comment]
> the latest version actually implement this.

Better than nothing.
